name: Metrics

on:
  schedule:
    - cron: "0 * * * *" # Update every hour
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_contributors: yes
          plugin_activity: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_habits: yes
          config_timezone: "auto" # Use your timezone, e.g., "America/New_York"
